version: '3'

services: 
    prometheus:
        image: prom/prometheus
        container_name: prometheus-container
        hostname: prometheus
        ports: 
            - "9090:9090"
        volumes: 
            - "./data-prometheus/:/etc/prometheus"
        # command: "--web.enable-lifecycle"
    
    blackbox-exporter:
        image: prom/blackbox-exporter
        container_name: blackbox-exporter-container
        hostname: blackbox-exporter
        ports: 
            - "9115:9115"
        volumes: 
            - "./data-blackbox/:/etc/blackbox_exporter/"

    grafana:
        image: grafana/grafana
        container_name: grafana-container
        hostname: grafana
        ports:
            - "3000:3000"
        volumes: 
            - "./data-grafana/:/var/lib/grafana"
    